### ISSUE TITLE
Plugin not loading for me?

### ISSUE THREAD

**Issue by NotAkitake** [Keplyx/cameras-and-drones#3]
I've put your smx in my plugins folder and the server doesn't load it.

**Comment by NotAkitake** [comment]
https://i.imgur.com/MZC5n7W.png

**Comment by Keplyx** [comment]
I'm not on my computer right now so I can't test, but it seems to me the plugin tries to load the custom drones file, but can't find it. Maybe try to add the custom_models.txt file to your installation (gamedata folder), hopefully it will fix the issue

**Comment by NotAkitake** [comment]
I did and it seems to be fine

**Comment by Keplyx** [comment]
This issue should be fixed in version 1.1.4
